// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorApp1.Models
{
    public partial class GetStudentSkillsResult
    {
        public int StudentId { get; set; }
        public int Skills { get; set; }
        public string SkillsName { get; set; }
    }
}
