// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorApp1.Models
{
    public partial class PaginationResult
    {
        public string Student_Name { get; set; }
        public DateTime Student_DOB { get; set; }
        public int Student_Age { get; set; }
        public string Student_Gender { get; set; }
        public int Student_Mobile { get; set; }
        public string Student_Address { get; set; }
        public bool IsDeleted { get; set; }
        public int Student_ID { get; set; }
    }
}
