// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models;

public partial class SkillsViewModel
{
    public int StudentId { get; set; }

    public int Skills { get; set; }

    public string SkillsName { get; set; }
}