// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp1.Models;

public partial class StudentDBContext : DbContext
{
    public StudentDBContext(DbContextOptions<StudentDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<StudentTable> StudentTables { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<StudentTable>(entity =>
        {
            entity.HasKey(e => e.StudentId).HasName("PK_Student_ID");

            entity.ToTable("Student_Table");

            entity.Property(e => e.StudentId).HasColumnName("Student_ID");
            entity.Property(e => e.StudentAddress)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Student_Address");
            entity.Property(e => e.StudentAge).HasColumnName("Student_Age");
            entity.Property(e => e.StudentDob)
                .HasColumnType("date")
                .HasColumnName("Student_DOB");
            entity.Property(e => e.StudentGender)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Student_Gender");
            entity.Property(e => e.StudentMobile).HasColumnName("Student_Mobile");
            entity.Property(e => e.StudentName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Student_Name");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}