// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models;

public partial class StudentTable
{
    public string StudentName { get; set; }

    public DateTime StudentDob { get; set; }

    public int StudentAge { get; set; }

    public string StudentGender { get; set; }

    public int StudentMobile { get; set; }

    public string StudentAddress { get; set; }

    public bool IsDeleted { get; set; }

    public int StudentId { get; set; }
}